
vich_uploader:
    db_driver: orm 
    mappings:
        assurance_images:
            uri_prefix: /images/constat 
            upload_destination: '%kernel.project_dir%/public/images/constat' 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
