controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
search_ateliers:
    path: /search-ateliers
    controller: App\Controller\SearchController::searchAtelier